//
//  SearchViewModel.swift
//  Chilesha
//
//  Created by shayne song on 4/7/25.
//

import Foundation

final class SearchViewModel: ObservableObject {
    @Published var showFoodCardView: Bool = false
    @Published var searchText: String = ""
    @Published var selectedFood: Food?
}

extension Double {
    static func dividedBy100(_ value: Double) -> Double {
        return value / 100.0
    }
    
    func dividedBy100() -> Double{
        return self / 100
    }
    
}

struct FoodData {
    static let data = [
        Food(name: "Apple", imageName: "apple", caloriesPer100g: 52.1, category: .fruit),
        Food(name: "Banana", imageName: "banana", caloriesPer100g: 88.7, category: .fruit),
        Food(name: "BlueBerry", imageName: "blueberries", caloriesPer100g: 57.7, category: .fruit),
        Food(name: "Broccoli", imageName: "broccoli", caloriesPer100g: 33.7,category: .vegetable),
        Food(name: "Drink", imageName: "drink1", caloriesPer100g: 100,  category: .beverage),
        Food(name: "Egg",  imageName: "egg", caloriesPer100g: 155.1,  category: .protein),
        Food(name: "Fish", imageName: "fish", caloriesPer100g: 205.8, category: .protein),
        Food(name: "Food",imageName: "food", caloriesPer100g: 100,  category: .other),
        Food(name: "Kiwi", imageName: "kiwi", caloriesPer100g: 60.9,  category: .fruit),
        Food(name: "Milk", imageName: "drink2", caloriesPer100g: 42.3, category: .dairy),
        Food(name: "Noodle", imageName: "noodle", caloriesPer100g: 138.1, category: .dairy),
        Food(name: "Corn",  imageName: "corn", caloriesPer100g: 71, category: .grain),
        Food(name: "Orange",  imageName: "orange", caloriesPer100g: 47.1,  category: .fruit),
        Food(name: "Pizza",  imageName: "pizza", caloriesPer100g: 266,  category: .fastfood),
        Food(name: "Potato",  imageName: "potato", caloriesPer100g: 87,  category: .vegetable),
        Food(name: "Pumpkin",  imageName: "pumpkin", caloriesPer100g: 46,  category: .vegetable),
        Food(name: "Shrimp",  imageName: "shrimp", caloriesPer100g: 91, category: .protein),
        Food(name: "Steak",  imageName: "steak", caloriesPer100g: 270, category: .protein),
        Food(name: "Strawberry",  imageName: "strawberry", caloriesPer100g: 32.5, category: .fruit),
        Food(name: "Sweet Potato",  imageName: "sweet-potato", caloriesPer100g: 84, category: .vegetable),
        Food(name: "Tomato",  imageName: "tomato", caloriesPer100g: 18, category: .vegetable),
        Food(name: "White Rice, cooked",  imageName: "white-rice", caloriesPer100g: 130, category: .grain),
        Food(name: "Yogurt",  imageName: "yogurt", caloriesPer100g: 58.8, category: .dairy),
        
        //beef chicken pork
        Food(name: "Beef",  imageName: "beef", caloriesPer100g: 156, category: .protein),
        Food(name: "Beef Bologna",  imageName: "beef", caloriesPer100g: 299,  category: .protein),
        Food(name: "Beef Brisket",  imageName: "beef", caloriesPer100g: 264, category: .protein),
        Food(name: "Beef Brisket",  imageName: "beef", caloriesPer100g: 333,  category: .protein),
        Food(name: "Beef Fillet, Beef Tenderloin",  imageName: "beef", caloriesPer100g: 121, category: .protein),
        Food(name: "Beef Heart",  imageName: "beef", caloriesPer100g: 105, category: .protein),
        Food(name: "Beef Kidney",  imageName: "beef", caloriesPer100g: 48,  category: .protein),
        Food(name: "Beef Liver",  imageName: "beef", caloriesPer100g: 131, category: .protein),
        Food(name: "Beef Noodle Soup",  imageName: "beef", caloriesPer100g: 70, category: .protein),
        Food(name: "Beef Patty",  imageName: "beef", caloriesPer100g: 295, category: .protein),
        Food(name: "Beef Ribs",  imageName: "beef", caloriesPer100g: 167,  category: .protein),
        Food(name: "Beef Roast",  imageName: "beef", caloriesPer100g: 216, category: .protein),
        Food(name: "Beef Sirloin",  imageName: "beef", caloriesPer100g: 360, category: .protein),
        Food(name: "Beef Stew",  imageName: "beef", caloriesPer100g: 251, category: .protein),
        Food(name: "Beef Stick",  imageName: "beef", caloriesPer100g: 583,  category: .protein),
        Food(name: "Beef Tallow",  imageName: "beef", caloriesPer100g: 902,  category: .protein),
        Food(name: "Beef Tongue",  imageName: "beef", caloriesPer100g: 221, category: .protein),
        Food(name: "Beef Tripe",  imageName: "beef", caloriesPer100g: 85,  category: .protein),
        Food(name: "Calf Liver",  imageName: "beef", caloriesPer100g: 113, category: .protein),
        Food(name: "Chuck Steak",  imageName: "beef", caloriesPer100g: 227, category: .protein),
        Food(name: "Corned Beef",  imageName: "beef", caloriesPer100g: 141, category: .protein),
        Food(name: "Corned Beef Hash",  imageName: "beef", caloriesPer100g: 164,category: .protein),
        Food(name: "Cubed Steak",  imageName: "beef", caloriesPer100g: 196,category: .protein),
        Food(name: "Filet Mignon",  imageName: "beef", caloriesPer100g: 98,category: .protein),
        Food(name: "Flank Steak",  imageName: "beef", caloriesPer100g: 165,  category: .protein),
        Food(name: "Flat Iron Steak",  imageName: "beef", caloriesPer100g: 182,category: .protein),
        Food(name: "Ground Beef",  imageName: "beef", caloriesPer100g: 208, category: .protein),
        Food(name: "Ground Beef, 85% lean",  imageName: "beef", caloriesPer100g: 215, category: .protein),
        Food(name: "Ground Beef, 90% lean",  imageName: "beef", caloriesPer100g: 176,  category: .protein),
        Food(name: "Ground Chuck",  imageName: "beef", caloriesPer100g: 250, category: .protein),
        Food(name: "Buffalo Wings",  imageName: "chicken", caloriesPer100g: 312, category: .protein),
        Food(name: "Chicken Breast",  imageName: "chicken", caloriesPer100g: 101, category: .protein),
        Food(name: "Chicken Breast Fillet",  imageName: "chicken", caloriesPer100g: 118, category: .protein),
        Food(name: "Chicken Breast, fried",  imageName: "chicken", caloriesPer100g: 105, category: .protein),
        Food(name: "Chicken Breast, grilled",  imageName: "chicken", caloriesPer100g: 107, category: .protein),
        Food(name: "Chicken Thigh",  imageName: "chicken", caloriesPer100g: 173, category: .protein),
        Food(name: "Chicken Thigh, cooked",  imageName: "chicken", caloriesPer100g: 141, category: .protein),
        Food(name: "Chicken Wings",  imageName: "chicken", caloriesPer100g: 191, category: .protein),
        Food(name: "Duck",  imageName: "chicken", caloriesPer100g: 227, category: .protein),
        Food(name: "Lamb",  imageName: "chicken", caloriesPer100g: 117, category: .protein),
        Food(name: "Meatball",  imageName: "chicken", caloriesPer100g: 214, category: .protein),
        Food(name: "Pork",  imageName: "pig", caloriesPer100g: 279, category: .protein),
        Food(name: "Pork Chop",  imageName: "pig", caloriesPer100g: 133, category: .protein),
        Food(name: "Rib Eye Steak",  imageName: "beef", caloriesPer100g: 241, category: .protein),
        
        
        
        //Bread
        Food(name: "Arepa",  imageName: "bread", caloriesPer100g: 267, category: .grain),
        Food(name: "Bagel, Cinnamon Raisin Bagel",  imageName: "bread", caloriesPer100g: 274, category: .grain),
        Food(name: "Bagel, Egg Bagel",  imageName: "bread", caloriesPer100g: 278, category: .grain),
        Food(name: "Bagel, Everything Bagel",  imageName: "bread", caloriesPer100g: 345, category: .grain),
        Food(name: "Bagel, Plain Bagel",  imageName: "bread", caloriesPer100g: 275,  category: .grain),
        Food(name: "Bagel, Sesame",  imageName: "bread", caloriesPer100g: 260,  category: .grain),
        Food(name: "Baguette, French Bread",  imageName: "bread", caloriesPer100g: 287,  category: .grain),
        Food(name: "Banana Bread",  imageName: "bread", caloriesPer100g: 270,  category: .grain),
        Food(name: "Banana Nut Bread",  imageName: "bread", caloriesPer100g: 364,  category: .grain),
        Food(name: "Beer Bread",  imageName: "bread", caloriesPer100g: 346,  category: .grain),
        Food(name: "Biscuit, plain or buttermilk",  imageName: "bread", caloriesPer100g: 353,  category: .grain),
        Food(name: "Bran Muffins",  imageName: "bread", caloriesPer100g: 270,  category: .grain),
        Food(name: "Bread Crumbs",  imageName: "bread", caloriesPer100g: 364,  category: .grain),
        Food(name: "Bread Roll",  imageName: "bread", caloriesPer100g: 279,  category: .grain),
        Food(name: "Wheat Bread",  imageName: "bread", caloriesPer100g: 246,  category: .grain),
        Food(name: "Wheat Bread",  imageName: "bread", caloriesPer100g: 246,  category: .grain),
        
        //seafood
        Food(name: "Abalone",  imageName: "seafood", caloriesPer100g: 209,  category: .seafood),
        Food(name: "Anchovis",  imageName: "seafood", caloriesPer100g: 101,  category: .seafood),
        Food(name: "Bass",  imageName: "seafood", caloriesPer100g: 98,  category: .seafood),
        Food(name: "Bluefish",  imageName: "seafood", caloriesPer100g: 124,  category: .seafood),
        Food(name: "Butterfish",  imageName: "seafood", caloriesPer100g: 114,  category: .seafood),
        Food(name: "Calamari",  imageName: "seafood", caloriesPer100g: 81,  category: .seafood),
        Food(name: "Carp",  imageName: "seafood", caloriesPer100g: 134,  category: .seafood),
        Food(name: "Caviar",  imageName: "seafood", caloriesPer100g: 260,  category: .seafood),
        Food(name: "Clam",  imageName: "seafood", caloriesPer100g: 86,  category: .seafood),
        Food(name: "Cod",  imageName: "seafood", caloriesPer100g: 77,  category: .seafood),
        Food(name: "Crawfish, Crayfish",  imageName: "seafood", caloriesPer100g: 81,  category: .seafood),
        Food(name: "Eel",  imageName: "seafood", caloriesPer100g: 281,  category: .seafood),
        Food(name: "Fish Fingers, Fish sticks",  imageName: "seafood", caloriesPer100g: 256,  category: .seafood),
        Food(name: "Flounder",  imageName: "seafood", caloriesPer100g: 72,  category: .seafood),
        Food(name: "Grouper",  imageName: "seafood", caloriesPer100g: 98,  category: .seafood),
        Food(name: "Haddock",  imageName: "seafood", caloriesPer100g: 77,  category: .seafood),
        Food(name: "Hake",  imageName: "seafood", caloriesPer100g: 94,  category: .seafood),
        Food(name: "Halibut",  imageName: "seafood", caloriesPer100g: 95,  category: .seafood),
        Food(name: "Herring",  imageName: "seafood", caloriesPer100g: 233,  category: .seafood),
        Food(name: "Kipper",  imageName: "seafood", caloriesPer100g: 164,  category: .seafood),
        Food(name: "Lobster",  imageName: "seafood", caloriesPer100g: 83,  category: .seafood),
        Food(name: "Mussel",  imageName: "seafood", caloriesPer100g: 69,  category: .seafood),
        Food(name: "Octopus",  imageName: "seafood", caloriesPer100g: 81,  category: .seafood),
        Food(name: "Oyster",  imageName: "seafood", caloriesPer100g: 66,  category: .seafood),
        Food(name: "Redfish",  imageName: "seafood", caloriesPer100g: 224,  category: .seafood),
        Food(name: "Salmon",  imageName: "seafood", caloriesPer100g: 180,  category: .seafood),
        Food(name: "Salmon Sashimi",  imageName: "seafood", caloriesPer100g: 180,  category: .seafood),
        Food(name: "Salmon, baked",  imageName: "seafood", caloriesPer100g: 112,  category: .seafood),
        Food(name: "Salmon, cooked",  imageName: "seafood", caloriesPer100g: 185,  category: .seafood),
        Food(name: "Scallop",  imageName: "seafood", caloriesPer100g: 73,  category: .seafood),
        Food(name: "Sea Bass",  imageName: "seafood", caloriesPer100g: 105,  category: .seafood),
        Food(name: "Shrimp",  imageName: "seafood", caloriesPer100g: 91,  category: .seafood),
        Food(name: "Shrimp, cooked",  imageName: "seafood", caloriesPer100g: 99,  category: .seafood),
        Food(name: "Shrimp, fried",  imageName: "seafood", caloriesPer100g: 105,  category: .seafood),
        Food(name: "Shrimp, grilled",  imageName: "seafood", caloriesPer100g: 105,  category: .seafood),
        Food(name: "Squid",  imageName: "seafood", caloriesPer100g: 81,  category: .seafood),
        Food(name: "Tilapia, cooked",  imageName: "seafood", caloriesPer100g: 128,  category: .seafood),
        Food(name: "Tuna",  imageName: "seafood", caloriesPer100g: 126,  category: .seafood),
        Food(name: "Tuna, canned",  imageName: "seafood", caloriesPer100g: 98,  category: .seafood),
        Food(name: "Tuna, canned in oil",  imageName: "seafood", caloriesPer100g: 353,  category: .seafood),
        Food(name: "White Fish",  imageName: "seafood", caloriesPer100g: 92,  category: .seafood),

        //fastfood
        Food(name: "BBQ Rib",  imageName: "fastfood", caloriesPer100g: 302,  category: .fastfood),
        Food(name: "BLT Sandwich",  imageName: "fastfood", caloriesPer100g: 205,  category: .fastfood),
        Food(name: "Baconator (Wendy's)",  imageName: "fastfood", caloriesPer100g: 445,  category: .fastfood),
        Food(name: "Bean Burrito",  imageName: "fastfood", caloriesPer100g: 221,  category: .fastfood),
        Food(name: "Beef Empanada",  imageName: "fastfood", caloriesPer100g: 333,  category: .fastfood),
        Food(name: "Big Mac (McDonald's)",  imageName: "fastfood", caloriesPer100g: 259,  category: .fastfood),
        Food(name: "Burger Patty",  imageName: "fastfood", caloriesPer100g: 212,  category: .fastfood),
        Food(name: "Cheese Quesadilla",  imageName: "fastfood", caloriesPer100g: 394,  category: .fastfood),
        Food(name: "Cheese Sandwich",  imageName: "fastfood", caloriesPer100g: 285,  category: .fastfood),
        Food(name: "Cheeseburger",  imageName: "fastfood", caloriesPer100g: 281,  category: .fastfood),
        Food(name: "Cheeseburger (McDonald's)",  imageName: "fastfood", caloriesPer100g: 254,  category: .fastfood),
        Food(name: "Chicken McNuggets (McDonald's)",  imageName: "fastfood", caloriesPer100g: 252,  category: .fastfood),
        Food(name: "Chicken Nuggets",  imageName: "fastfood", caloriesPer100g: 252,  category: .fastfood),
        Food(name: "Chicken Nuggets (McDonald's)",  imageName: "fastfood", caloriesPer100g: 252,  category: .fastfood),
        Food(name: "Chicken Sandwich",  imageName: "fastfood", caloriesPer100g: 249,  category: .fastfood),
        Food(name: "Chicken Tenders",  imageName: "fastfood", caloriesPer100g: 271,  category: .fastfood),
        Food(name: "Chicken Wings",  imageName: "fastfood", caloriesPer100g: 191,  category: .fastfood),
        Food(name: "Chimichanga",  imageName: "fastfood", caloriesPer100g: 246,  category: .fastfood),
        Food(name: "Chinese Egg Roll",  imageName: "fastfood", caloriesPer100g: 269,  category: .fastfood),
        Food(name: "Corn Dog",  imageName: "fastfood", caloriesPer100g: 250,  category: .fastfood),
        Food(name: "Crispy Chicken Sandwich",  imageName: "fastfood", caloriesPer100g: 276,  category: .fastfood),
        Food(name: "Double Cheeseburger",  imageName: "fastfood", caloriesPer100g: 269,  category: .fastfood),
        Food(name: "Double Cheeseburger (McDonald's)",  imageName: "fastfood", caloriesPer100g: 282,  category: .fastfood),
        Food(name: "Double Whopper (Burger King)",  imageName: "fastfood", caloriesPer100g: 252,  category: .fastfood),
        Food(name: "Double Whopper, with cheese (Burger King)",  imageName: "fastfood", caloriesPer100g: 266,  category: .fastfood),
        Food(name: "Egg McMuffin (McDonald's)",  imageName: "fastfood", caloriesPer100g: 256,  category: .fastfood),
        Food(name: "Egg Roll",  imageName: "fastfood", caloriesPer100g: 307,  category: .fastfood),
        Food(name: "Egg Sandwich",  imageName: "fastfood", caloriesPer100g: 298,  category: .fastfood),
        Food(name: "Filet o Fish (McDonald's)",  imageName: "fastfood", caloriesPer100g: 282,  category: .fastfood),
        Food(name: "Fish Sandwich",  imageName: "fastfood", caloriesPer100g: 194,  category: .fastfood),
        Food(name: "French Fries",  imageName: "fastfood", caloriesPer100g: 312,  category: .fastfood),
        Food(name: "French Fries, large",  imageName: "fastfood", caloriesPer100g: 289,  category: .fastfood),
        Food(name: "French Toast Sticks",  imageName: "fastfood", caloriesPer100g: 340,  category: .fastfood),
        Food(name: "Grilled Chicken Sandwich",  imageName: "fastfood", caloriesPer100g: 182,  category: .fastfood),
        Food(name: "Hamburger",  imageName: "fastfood", caloriesPer100g: 297,  category: .fastfood),
        Food(name: "Hot Dog",  imageName: "fastfood", caloriesPer100g: 235,  category: .fastfood),
        Food(name: "Hot Dog Bun, Hotdog Roll",  imageName: "fastfood", caloriesPer100g: 469,  category: .fastfood),
        Food(name: "Hot Dog with Chili",  imageName: "fastfood", caloriesPer100g: 260,  category: .fastfood),
        Food(name: "Hot Wings",  imageName: "fastfood", caloriesPer100g: 252,  category: .fastfood),
        Food(name: "Hushpuppies",  imageName: "fastfood", caloriesPer100g: 245,  category: .fastfood),
        Food(name: "Instant Ramen",  imageName: "fastfood", caloriesPer100g: 67,  category: .fastfood),
        Food(name: "Italian BMT (Subway)",  imageName: "fastfood", caloriesPer100g: 540,  category: .fastfood),
        Food(name: "Jr Bacon Cheeseburger (Wendy's)",  imageName: "fastfood", caloriesPer100g: 271,  category: .fastfood),
        Food(name: "Jr Cheeseburger (Wendy's)",  imageName: "fastfood", caloriesPer100g: 208,  category: .fastfood),
        Food(name: "Kebab",  imageName: "fastfood", caloriesPer100g: 158,  category: .fastfood),
        Food(name: "McChicken (McDonald's)",  imageName: "fastfood", caloriesPer100g: 230,  category: .fastfood),
        Food(name: "McDouble (McDonald's)",  imageName: "fastfood", caloriesPer100g: 282,  category: .fastfood),
        Food(name: "McRib (McDonald's)",  imageName: "fastfood", caloriesPer100g: 226,  category: .fastfood),
        Food(name: "Nachos Supreme",  imageName: "fastfood", caloriesPer100g: 367,  category: .fastfood),
        Food(name: "Onion Rings",  imageName: "fastfood", caloriesPer100g: 252,  category: .fastfood),
        Food(name: "Original Chicken Sandwich (Burger King)",  imageName: "fastfood", caloriesPer100g: 286,  category: .fastfood),
        Food(name: "Peanut Butter Sandwich",  imageName: "fastfood", caloriesPer100g: 384,  category: .fastfood),
        Food(name: "Poutine",  imageName: "fastfood", caloriesPer100g: 288,  category: .fastfood),
        Food(name: "Quarter Pounder (McDonald's)",  imageName: "fastfood", caloriesPer100g: 256,  category: .fastfood),
        Food(name: "Quarter Pounder with Cheese (McDonald's)",  imageName: "fastfood", caloriesPer100g: 258,  category: .fastfood),
        Food(name: "Reuben Sandwich (Arby's)",  imageName: "fastfood", caloriesPer100g: 282,  category: .fastfood),
        Food(name: "Roast Beef Sandwich",  imageName: "fastfood", caloriesPer100g: 192,  category: .fastfood),
        Food(name: "Sausage Biscuit",  imageName: "fastfood", caloriesPer100g: 350,  category: .fastfood),
        Food(name: "Sausage Burrito",  imageName: "fastfood", caloriesPer100g: 277,  category: .fastfood),
        Food(name: "Sausage McGriddles (McDonald's)",  imageName: "fastfood", caloriesPer100g: 312,  category: .fastfood),
        Food(name: "Sausage McMuffin (McDonald's)",  imageName: "fastfood", caloriesPer100g: 333,  category: .fastfood),
        Food(name: "Sloppy Joe",  imageName: "fastfood", caloriesPer100g: 321,  category: .fastfood),
        Food(name: "Spring Roll",  imageName: "fastfood", caloriesPer100g: 212,  category: .fastfood),
        Food(name: "Taco Salad",  imageName: "fastfood", caloriesPer100g: 500,  category: .fastfood),
        Food(name: "Vegan Hot Dogs",  imageName: "fastfood", caloriesPer100g: 204,  category: .fastfood),
        Food(name: "Veggie Burger",  imageName: "fastfood", caloriesPer100g: 204,  category: .fastfood),
        Food(name: "Whopper (Burger King)",  imageName: "fastfood", caloriesPer100g: 233,  category: .fastfood),
        Food(name: "Whopper, with cheese (Burger King)",  imageName: "fastfood", caloriesPer100g: 250,  category: .fastfood),
        Food(name: "Zinger Burger (KFC)",  imageName: "fastfood", caloriesPer100g: 244,  category: .fastfood),
        
        //fruit
        Food(name: "Asian Pear",  imageName: "fruit", caloriesPer100g: 42,  category: .fruit),
        Food(name: "Blackberries",  imageName: "fruit", caloriesPer100g: 43,  category: .fruit),
        Food(name: "Blood Orange",  imageName: "fruit", caloriesPer100g: 43,  category: .fruit),
        Food(name: "Breadfruit",  imageName: "fruit", caloriesPer100g: 103,  category: .fruit),
        Food(name: "Cactus Pear",  imageName: "fruit", caloriesPer100g: 46,  category: .fruit),
        Food(name: "Cantaloupe",  imageName: "fruit", caloriesPer100g: 56,  category: .fruit),
        Food(name: "Carob",  imageName: "fruit", caloriesPer100g: 188,  category: .fruit),
        Food(name: "Chayote",  imageName: "fruit", caloriesPer100g: 19,  category: .fruit),
        Food(name: "Cherries",  imageName: "fruit", caloriesPer100g: 64,  category: .fruit),
        Food(name: "Clementine",  imageName: "fruit", caloriesPer100g: 49,  category: .fruit),
        Food(name: "Coconut",  imageName: "fruit", caloriesPer100g: 384,  category: .fruit),
        Food(name: "Concord Grape",  imageName: "fruit", caloriesPer100g: 86,  category: .fruit),
        Food(name: "Cranberries",  imageName: "fruit", caloriesPer100g: 76,  category: .fruit),
        Food(name: "Cranberries, dried",  imageName: "fruit", caloriesPer100g: 315,  category: .fruit),
        Food(name: "Currant",  imageName: "fruit", caloriesPer100g: 40,  category: .fruit),
        Food(name: "Dates",  imageName: "fruit", caloriesPer100g: 294,  category: .fruit),
        Food(name: "Dates, Medjool Dates",  imageName: "fruit", caloriesPer100g: 277,  category: .fruit),
        Food(name: "Dragon Fruit",  imageName: "fruit", caloriesPer100g: 60,  category: .fruit),
        Food(name: "Dried Fruit Mix",  imageName: "fruit", caloriesPer100g: 258,  category: .fruit),
        Food(name: "Durian",  imageName: "fruit", caloriesPer100g: 151,  category: .fruit),
        Food(name: "Elderberries",  imageName: "fruit", caloriesPer100g: 348,  category: .fruit),
        Food(name: "Fig",  imageName: "fruit", caloriesPer100g: 66,  category: .fruit),
        Food(name: "Fig, dried",  imageName: "fruit", caloriesPer100g: 270,  category: .fruit),
        Food(name: "Fruit Salad, Mixed Fruit",  imageName: "fruit", caloriesPer100g: 63,  category: .fruit),
        Food(name: "Goji Berry",  imageName: "fruit", caloriesPer100g: 325,  category: .fruit),
        Food(name: "Gooseberries",  imageName: "fruit", caloriesPer100g: 43,  category: .fruit),
        Food(name: "Grapefruit",  imageName: "fruit", caloriesPer100g: 47,  category: .fruit),
        Food(name: "Grapes",  imageName: "fruit", caloriesPer100g: 72,  category: .fruit),
        Food(name: "Guava",  imageName: "fruit", caloriesPer100g: 44,  category: .fruit),
        Food(name: "Huckleberry",  imageName: "fruit", caloriesPer100g: 429,  category: .fruit),
        Food(name: "Jackfruit",  imageName: "fruit", caloriesPer100g: 80,  category: .fruit),
        Food(name: "Jujube",  imageName: "fruit", caloriesPer100g: 115,  category: .fruit),
        Food(name: "Lemon",  imageName: "fruit", caloriesPer100g: 38,  category: .fruit),
        Food(name: "Lime",  imageName: "fruit", caloriesPer100g: 48,  category: .fruit),
        Food(name: "Longan",  imageName: "fruit", caloriesPer100g: 74,  category: .fruit),
        Food(name: "Lychee",  imageName: "fruit", caloriesPer100g: 78,  category: .fruit),
        Food(name: "Mandarin Orange",  imageName: "fruit", caloriesPer100g: 53,  category: .fruit),
        Food(name: "Mango",  imageName: "fruit", caloriesPer100g: 61,  category: .fruit),
        Food(name: "Melon, Galia Melon",  imageName: "fruit", caloriesPer100g: 56,  category: .fruit),
        Food(name: "Melon, Honeydew Melon",  imageName: "fruit", caloriesPer100g: 56,  category: .fruit),
        Food(name: "Melon, Musk melon",  imageName: "fruit", caloriesPer100g: 56,  category: .fruit),
        Food(name: "Melon, Water Melon",  imageName: "fruit", caloriesPer100g: 38,  category: .fruit),
        Food(name: "Melon, Winter Melon",  imageName: "fruit", caloriesPer100g: 30,  category: .fruit),
        Food(name: "Melon, Yellow Melon",  imageName: "fruit", caloriesPer100g: 30,  category: .fruit),
        Food(name: "Mixed Berries, frozen",  imageName: "fruit", caloriesPer100g: 67,  category: .fruit),
        Food(name: "Mulberries",  imageName: "fruit", caloriesPer100g: 47,  category: .fruit),
        Food(name: "Orange",  imageName: "fruit", caloriesPer100g: 47,  category: .fruit),
        Food(name: "Papaya",  imageName: "fruit", caloriesPer100g: 35,  category: .fruit),
        Food(name: "Passion Fruit",  imageName: "fruit", caloriesPer100g: 66,  category: .fruit),
        Food(name: "Pawpaw",  imageName: "fruit", caloriesPer100g: 80,  category: .fruit),
        Food(name: "Peach",  imageName: "fruit", caloriesPer100g: 44,  category: .fruit),
        Food(name: "Pear",  imageName: "fruit", caloriesPer100g: 57,  category: .fruit),
        Food(name: "Pineapple",  imageName: "fruit", caloriesPer100g: 58,  category: .fruit),
        Food(name: "Plum",  imageName: "fruit", caloriesPer100g: 48,  category: .fruit),
        Food(name: "Strawberries",  imageName: "fruit", caloriesPer100g: 36,  category: .fruit),
        Food(name: "Tamarind",  imageName: "fruit", caloriesPer100g: 290,  category: .fruit),
        Food(name: "Tangelo",  imageName: "fruit", caloriesPer100g: 53,  category: .fruit),
        Food(name: "Tomatillo",  imageName: "fruit", caloriesPer100g: 32,  category: .fruit),

        //dairy
        Food(name: "Actimel (Danone)",  imageName: "dairy", caloriesPer100g: 73,  category: .dairy),
        Food(name: "Almond Milk",  imageName: "dairy", caloriesPer100g: 22,  category: .dairy),
        Food(name: "Butter",  imageName: "dairy", caloriesPer100g: 754,  category: .dairy),
        Food(name: "Buttermilk",  imageName: "dairy", caloriesPer100g: 37,  category: .dairy),
        Food(name: "Chocolate Milk",  imageName: "dairy", caloriesPer100g: 132,  category: .dairy),
        Food(name: "Coconut Milk",  imageName: "dairy", caloriesPer100g: 230,  category: .dairy),
        Food(name: "Coffee Creamer",  imageName: "dairy", caloriesPer100g: 206,  category: .dairy),
        Food(name: "Condensed Milk",  imageName: "dairy", caloriesPer100g: 132,  category: .dairy),
        Food(name: "Condensed Milk, sweetened",  imageName: "dairy", caloriesPer100g: 321,  category: .dairy),
        Food(name: "Cream",  imageName: "dairy", caloriesPer100g: 308,  category: .dairy),
        Food(name: "Creme Fraiche",  imageName: "dairy", caloriesPer100g: 281,  category: .dairy),
        Food(name: "Goat Milk",  imageName: "dairy", caloriesPer100g: 67,  category: .dairy),
        Food(name: "Greek Yogurt",  imageName: "dairy", caloriesPer100g: 116,  category: .dairy),
        Food(name: "Half and Half Cream",  imageName: "dairy", caloriesPer100g: 131,  category: .dairy),
        Food(name: "Heavy Cream, Heavy Whipping Cream",  imageName: "dairy", caloriesPer100g: 343,  category: .dairy),
        Food(name: "Hot Chocolate",  imageName: "dairy", caloriesPer100g: 132,  category: .dairy),
        Food(name: "Kefir",  imageName: "dairy", caloriesPer100g: 65,  category: .dairy),
        Food(name: "Lactose Free Milk",  imageName: "dairy", caloriesPer100g: 39,  category: .dairy),
        Food(name: "Lassi",  imageName: "dairy", caloriesPer100g: 65,  category: .dairy),
        Food(name: "Malted Milk",  imageName: "dairy", caloriesPer100g: 58,  category: .dairy),
        Food(name: "Mango Lassi",  imageName: "dairy", caloriesPer100g: 82,  category: .dairy),
        Food(name: "Mascarpone",  imageName: "dairy", caloriesPer100g: 393,  category: .dairy),
        Food(name: "Milk, 1.5% fat, low-fat",  imageName: "dairy", caloriesPer100g: 48,  category: .dairy),
        Food(name: "Milk, 2% fat, low fat",  imageName: "dairy", caloriesPer100g: 50,  category: .dairy),
        Food(name: "Milk, Whole Milk, Full Fat Milk",  imageName: "dairy", caloriesPer100g: 65,  category: .dairy),
        Food(name: "Milk, fat free",  imageName: "dairy", caloriesPer100g: 34,  category: .dairy),
        Food(name: "Milkshake, Strawberry",  imageName: "dairy", caloriesPer100g: 165,  category: .dairy),
        Food(name: "Milkshake, Vanilla",  imageName: "dairy", caloriesPer100g: 78,  category: .dairy),
        Food(name: "Natural Yoghurt, plain",  imageName: "dairy", caloriesPer100g: 69,  category: .dairy),
        Food(name: "Powdered Milk, Milk Powder",  imageName: "dairy", caloriesPer100g: 482,  category: .dairy),
        Food(name: "Rice Milk",  imageName: "dairy", caloriesPer100g: 53,  category: .dairy),
        Food(name: "Semi Skimmed Milk",  imageName: "dairy", caloriesPer100g: 47,  category: .dairy),
        Food(name: "Sheep Milk",  imageName: "dairy", caloriesPer100g: 94,  category: .dairy),
        Food(name: "Skim Milk",  imageName: "dairy", caloriesPer100g: 35,  category: .dairy),
        Food(name: "Soy Milk",  imageName: "dairy", caloriesPer100g: 36,  category: .dairy),
        Food(name: "Whipped Cream, Whipping Cream",  imageName: "dairy", caloriesPer100g: 308,  category: .dairy),
        Food(name: "Yakult",  imageName: "dairy", caloriesPer100g: 67,  category: .dairy),
        Food(name: "Yougurt, plain",  imageName: "dairy", caloriesPer100g: 69,  category: .dairy),
        
        // potatos
        Food(name: "Baked Potato",  imageName: "potato", caloriesPer100g: 122,  category: .vegetable),
        Food(name: "Croquettes",  imageName: "potato", caloriesPer100g: 180,  category: .vegetable),
        Food(name: "Gnocchi",  imageName: "potato", caloriesPer100g: 163,  category: .vegetable),
        Food(name: "Hash Browns",  imageName: "potato", caloriesPer100g: 173,  category: .vegetable),
        Food(name: "Latkes",  imageName: "potato", caloriesPer100g: 194,  category: .vegetable),
        Food(name: "Mashed Potato",  imageName: "potato", caloriesPer100g: 93,  category: .vegetable),
        Food(name: "Mashed Potato, with Milk and Butter",  imageName: "potato", caloriesPer100g: 74,  category: .vegetable),
        Food(name: "Potato Flour",  imageName: "potato", caloriesPer100g: 268,  category: .vegetable),
        Food(name: "Potato Salad",  imageName: "potato", caloriesPer100g: 105,  category: .vegetable),
        Food(name: "Potato Salad, with Egg",  imageName: "potato", caloriesPer100g: 250,  category: .vegetable),
        Food(name: "Potato Waffles",  imageName: "potato", caloriesPer100g: 190,  category: .vegetable),
        Food(name: "Potato Wedges",  imageName: "potato", caloriesPer100g: 162,  category: .vegetable),
        Food(name: "Potato, baked, Baked Potato with Sour Cream",  imageName: "potato", caloriesPer100g: 130,  category: .vegetable),
        Food(name: "Potato, boiled",  imageName: "potato", caloriesPer100g: 88,  category: .vegetable),
        Food(name: "Potato, fried",  imageName: "potato", caloriesPer100g: 104,  category: .vegetable),
        Food(name: "Potatoes au Gratin, Potato Gratin, Scalloped Potatoes",  imageName: "potato", caloriesPer100g: 113,  category: .vegetable),
        Food(name: "Red Potato",  imageName: "potato", caloriesPer100g: 70,  category: .vegetable),
        Food(name: "Roast Potato",  imageName: "potato", caloriesPer100g: 152,  category: .vegetable),
        Food(name: "Yam",  imageName: "potato", caloriesPer100g: 116,  category: .vegetable),
        
        //rice
        Food(name: "Basmati Rice",  imageName: "rice", caloriesPer100g: 352,  category: .grain),
        Food(name: "Black Rice",  imageName: "rice", caloriesPer100g: 362,  category: .grain),
        Food(name: "Brown Rice",  imageName: "rice", caloriesPer100g: 367,  category: .grain),
        Food(name: "Brown Rice, cooked",  imageName: "rice", caloriesPer100g: 147,  category: .grain),
        Food(name: "Fried Rice",  imageName: "rice", caloriesPer100g: 125,  category: .grain),
        Food(name: "Idly Rice",  imageName: "rice", caloriesPer100g: 128,  category: .grain),
        Food(name: "Jasmine Rice",  imageName: "rice", caloriesPer100g: 356,  category: .grain),
        Food(name: "Puffed Rice",  imageName: "rice", caloriesPer100g: 389,  category: .grain),
        Food(name: "Rice Bran",  imageName: "rice", caloriesPer100g: 402,  category: .grain),
        Food(name: "Rice Bran Oil",  imageName: "rice", caloriesPer100g: 884,  category: .grain),
        Food(name: "Rice Cake",  imageName: "rice", caloriesPer100g: 387,  category: .grain),
        Food(name: "Rice Crackers",  imageName: "rice", caloriesPer100g: 389,  category: .grain),
        Food(name: "Rice Crisps",  imageName: "rice", caloriesPer100g: 384,  category: .grain),
        Food(name: "Rice Noodles, cooked",  imageName: "rice", caloriesPer100g: 107,  category: .grain),
        Food(name: "Shirataki Rice",  imageName: "rice", caloriesPer100g: 9,  category: .grain),
        Food(name: "White Rice",  imageName: "rice", caloriesPer100g: 350,  category: .grain),



    ]
}
